apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: ingress
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "31.*"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    deployment:
      replicas: 1
    service:
      type: ClusterIP
    ports:
      web:
        port: 8000
        expose:
          default: true
        exposedPort: 80
        hostPort: 80
      websecure:
        port: 8443
        expose:
          default: true
        exposedPort: 443
        hostPort: 443
        tls:
          enabled: true
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespaceIngress: true
      kubernetesIngress:
        enabled: true
    api:
      dashboard: true
      insecure: false
    logs:
      access:
        enabled: true
    additionalArguments:
      - "--providers.kubernetesCRD.allowExternalNameServices=true"
    securityContext:
      runAsNonRoot: true
      runAsUser: 65532
      runAsGroup: 65532
