---
apiVersion: v1
kind: Secret
metadata:
  name: ${VMNAME}-cloudinit
  namespace: vms
  labels:
    app.kubernetes.io/name: ${VMNAME}
    app.kubernetes.io/part-of: kubevirt-migration
type: Opaque
stringData:
  userdata: |
    #cloud-config
