---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ${VMNAME}-rootdisk
  namespace: vms
  labels:
    app.kubernetes.io/name: ${VMNAME}
    app.kubernetes.io/part-of: kubevirt-migration
  annotations:
    homelab.telometto.io/source-image: debian-13-genericcloud-amd64
spec:
  source:
    http:
      url: https://cloud.debian.org/images/cloud/trixie/latest/debian-13-genericcloud-amd64.qcow2
  pvc:
    storageClassName: kubevirt-local-immediate
    volumeName: ${VMNAME}-rootdisk
    volumeMode: Filesystem
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi  # TODO: update per VM
