apiVersion: v1
kind: PersistentVolume
metadata:
  name: actual-rootdisk
  labels:
    app.kubernetes.io/name: actual
    app.kubernetes.io/part-of: kubevirt-migration
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kubevirt-local-immediate
  local:
    path: /flash/enc/kubevirt/actual/rootdisk
  claimRef:
    namespace: vms
    name: actual-rootdisk
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - blizzard
