apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - network.yaml
  - network-config-kustomization.yaml
  - sealed-secrets.yaml
  - ingress.yaml
  - kubevirt.yaml
  - kubevirt-config.yaml
  - cdi.yaml
  - cdi-config.yaml
  - storage.yaml
  - vms.yaml
